# Generated by Django 4.1.3 on 2022-12-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaseapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='bio',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
